[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.3.0"
edition = "2024"
rust-version = "1.93"
license = "GPL-3.0-or-later"
repository = "https://github.com/Astra-Interactive/NanoLimbo-rs"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
indexing_slicing = "warn"
panic = "warn"
unwrap_used = "warn"
expect_used = "warn"

[workspace.dependencies]
bytes = "1"
flate2 = "1"
hmac = "0.12"
md-5 = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_yaml_ng = "0.10"
sha2 = "0.10"
subtle = "2"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "time", "sync", "signal", "macros"] }
tokio-util = { version = "0.7", features = ["codec"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
uuid = { version = "1", features = ["v3", "v4"] }
valence_nbt = { version = "0.8", features = ["binary", "preserve_order"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
