[package]
name = "nanolimbo"
description = "A lightweight Minecraft limbo server."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bytes.workspace = true
futures-util = { version = "0.3", default-features = false, features = ["std", "sink"] }
limbo-config = { path = "../limbo-config" }
limbo-net = { path = "../limbo-net" }
limbo-packet = { path = "../limbo-packet" }
limbo-protocol = { path = "../limbo-protocol" }
limbo-server = { path = "../limbo-server" }
limbo-text = { path = "../limbo-text" }
limbo-world = { path = "../limbo-world" }
rand = "0.9"
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[lints]
workspace = true
